/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getSystemInfo(): Array<string>

export declare function plus100(input: number): number

export declare function plus200(input: number): number
